/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AttacklabRouteImport } from './routes/attacklab'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as ConsoleRouteImport } from './routes/console'
import { Route as DecisionsRouteImport } from './routes/decisions'
import { Route as DifferencingRouteImport } from './routes/differencing'
import { Route as FederatedRouteImport } from './routes/federated'
import { Route as GuidedRouteImport } from './routes/guided'
import { Route as HealthRouteImport } from './routes/health'
import { Route as InfrastructureRouteImport } from './routes/infrastructure'
import { Route as LedgerRouteImport } from './routes/ledger'
import { Route as MlRouteImport } from './routes/ml'
import { Route as MonitorRouteImport } from './routes/monitor'
import { Route as OverviewRouteImport } from './routes/overview'
import { Route as PipelineRouteImport } from './routes/pipeline'
import { Route as PolicyRouteImport } from './routes/policy'
import { Route as PrevalenceRouteImport } from './routes/prevalence'
import { Route as ThreatRouteImport } from './routes/threat'
import { Route as TradeoffRouteImport } from './routes/tradeoff'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AttacklabRoute = AttacklabRouteImport.update({
  id: '/attacklab',
  path: '/attacklab',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleRoute = ConsoleRouteImport.update({
  id: '/console',
  path: '/console',
  getParentRoute: () => rootRouteImport,
} as any)
const DecisionsRoute = DecisionsRouteImport.update({
  id: '/decisions',
  path: '/decisions',
  getParentRoute: () => rootRouteImport,
} as any)
const DifferencingRoute = DifferencingRouteImport.update({
  id: '/differencing',
  path: '/differencing',
  getParentRoute: () => rootRouteImport,
} as any)
const FederatedRoute = FederatedRouteImport.update({
  id: '/federated',
  path: '/federated',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidedRoute = GuidedRouteImport.update({
  id: '/guided',
  path: '/guided',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const InfrastructureRoute = InfrastructureRouteImport.update({
  id: '/infrastructure',
  path: '/infrastructure',
  getParentRoute: () => rootRouteImport,
} as any)
const LedgerRoute = LedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => rootRouteImport,
} as any)
const MlRoute = MlRouteImport.update({
  id: '/ml',
  path: '/ml',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitorRoute = MonitorRouteImport.update({
  id: '/monitor',
  path: '/monitor',
  getParentRoute: () => rootRouteImport,
} as any)
const OverviewRoute = OverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineRoute = PipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const PolicyRoute = PolicyRouteImport.update({
  id: '/policy',
  path: '/policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PrevalenceRoute = PrevalenceRouteImport.update({
  id: '/prevalence',
  path: '/prevalence',
  getParentRoute: () => rootRouteImport,
} as any)
const ThreatRoute = ThreatRouteImport.update({
  id: '/threat',
  path: '/threat',
  getParentRoute: () => rootRouteImport,
} as any)
const TradeoffRoute = TradeoffRouteImport.update({
  id: '/tradeoff',
  path: '/tradeoff',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/attacklab': typeof AttacklabRoute
  '/audit': typeof AuditRoute
  '/console': typeof ConsoleRoute
  '/decisions': typeof DecisionsRoute
  '/differencing': typeof DifferencingRoute
  '/federated': typeof FederatedRoute
  '/guided': typeof GuidedRoute
  '/health': typeof HealthRoute
  '/infrastructure': typeof InfrastructureRoute
  '/ledger': typeof LedgerRoute
  '/ml': typeof MlRoute
  '/monitor': typeof MonitorRoute
  '/overview': typeof OverviewRoute
  '/pipeline': typeof PipelineRoute
  '/policy': typeof PolicyRoute
  '/prevalence': typeof PrevalenceRoute
  '/threat': typeof ThreatRoute
  '/tradeoff': typeof TradeoffRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/attacklab': typeof AttacklabRoute
  '/audit': typeof AuditRoute
  '/console': typeof ConsoleRoute
  '/decisions': typeof DecisionsRoute
  '/differencing': typeof DifferencingRoute
  '/federated': typeof FederatedRoute
  '/guided': typeof GuidedRoute
  '/health': typeof HealthRoute
  '/infrastructure': typeof InfrastructureRoute
  '/ledger': typeof LedgerRoute
  '/ml': typeof MlRoute
  '/monitor': typeof MonitorRoute
  '/overview': typeof OverviewRoute
  '/pipeline': typeof PipelineRoute
  '/policy': typeof PolicyRoute
  '/prevalence': typeof PrevalenceRoute
  '/threat': typeof ThreatRoute
  '/tradeoff': typeof TradeoffRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/attacklab': typeof AttacklabRoute
  '/audit': typeof AuditRoute
  '/console': typeof ConsoleRoute
  '/decisions': typeof DecisionsRoute
  '/differencing': typeof DifferencingRoute
  '/federated': typeof FederatedRoute
  '/guided': typeof GuidedRoute
  '/health': typeof HealthRoute
  '/infrastructure': typeof InfrastructureRoute
  '/ledger': typeof LedgerRoute
  '/ml': typeof MlRoute
  '/monitor': typeof MonitorRoute
  '/overview': typeof OverviewRoute
  '/pipeline': typeof PipelineRoute
  '/policy': typeof PolicyRoute
  '/prevalence': typeof PrevalenceRoute
  '/threat': typeof ThreatRoute
  '/tradeoff': typeof TradeoffRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/attacklab'
    | '/audit'
    | '/console'
    | '/decisions'
    | '/differencing'
    | '/federated'
    | '/guided'
    | '/health'
    | '/infrastructure'
    | '/ledger'
    | '/ml'
    | '/monitor'
    | '/overview'
    | '/pipeline'
    | '/policy'
    | '/prevalence'
    | '/threat'
    | '/tradeoff'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/attacklab'
    | '/audit'
    | '/console'
    | '/decisions'
    | '/differencing'
    | '/federated'
    | '/guided'
    | '/health'
    | '/infrastructure'
    | '/ledger'
    | '/ml'
    | '/monitor'
    | '/overview'
    | '/pipeline'
    | '/policy'
    | '/prevalence'
    | '/threat'
    | '/tradeoff'
  id:
    | '__root__'
    | '/'
    | '/attacklab'
    | '/audit'
    | '/console'
    | '/decisions'
    | '/differencing'
    | '/federated'
    | '/guided'
    | '/health'
    | '/infrastructure'
    | '/ledger'
    | '/ml'
    | '/monitor'
    | '/overview'
    | '/pipeline'
    | '/policy'
    | '/prevalence'
    | '/threat'
    | '/tradeoff'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AttacklabRoute: typeof AttacklabRoute
  AuditRoute: typeof AuditRoute
  ConsoleRoute: typeof ConsoleRoute
  DecisionsRoute: typeof DecisionsRoute
  DifferencingRoute: typeof DifferencingRoute
  FederatedRoute: typeof FederatedRoute
  GuidedRoute: typeof GuidedRoute
  HealthRoute: typeof HealthRoute
  InfrastructureRoute: typeof InfrastructureRoute
  LedgerRoute: typeof LedgerRoute
  MlRoute: typeof MlRoute
  MonitorRoute: typeof MonitorRoute
  OverviewRoute: typeof OverviewRoute
  PipelineRoute: typeof PipelineRoute
  PolicyRoute: typeof PolicyRoute
  PrevalenceRoute: typeof PrevalenceRoute
  ThreatRoute: typeof ThreatRoute
  TradeoffRoute: typeof TradeoffRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attacklab': {
      id: '/attacklab'
      path: '/attacklab'
      fullPath: '/attacklab'
      preLoaderRoute: typeof AttacklabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console': {
      id: '/console'
      path: '/console'
      fullPath: '/console'
      preLoaderRoute: typeof ConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decisions': {
      id: '/decisions'
      path: '/decisions'
      fullPath: '/decisions'
      preLoaderRoute: typeof DecisionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/differencing': {
      id: '/differencing'
      path: '/differencing'
      fullPath: '/differencing'
      preLoaderRoute: typeof DifferencingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/federated': {
      id: '/federated'
      path: '/federated'
      fullPath: '/federated'
      preLoaderRoute: typeof FederatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guided': {
      id: '/guided'
      path: '/guided'
      fullPath: '/guided'
      preLoaderRoute: typeof GuidedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/infrastructure': {
      id: '/infrastructure'
      path: '/infrastructure'
      fullPath: '/infrastructure'
      preLoaderRoute: typeof InfrastructureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ledger': {
      id: '/ledger'
      path: '/ledger'
      fullPath: '/ledger'
      preLoaderRoute: typeof LedgerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ml': {
      id: '/ml'
      path: '/ml'
      fullPath: '/ml'
      preLoaderRoute: typeof MlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitor': {
      id: '/monitor'
      path: '/monitor'
      fullPath: '/monitor'
      preLoaderRoute: typeof MonitorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overview': {
      id: '/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof OverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline': {
      id: '/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof PipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policy': {
      id: '/policy'
      path: '/policy'
      fullPath: '/policy'
      preLoaderRoute: typeof PolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prevalence': {
      id: '/prevalence'
      path: '/prevalence'
      fullPath: '/prevalence'
      preLoaderRoute: typeof PrevalenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/threat': {
      id: '/threat'
      path: '/threat'
      fullPath: '/threat'
      preLoaderRoute: typeof ThreatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tradeoff': {
      id: '/tradeoff'
      path: '/tradeoff'
      fullPath: '/tradeoff'
      preLoaderRoute: typeof TradeoffRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AttacklabRoute: AttacklabRoute,
  AuditRoute: AuditRoute,
  ConsoleRoute: ConsoleRoute,
  DecisionsRoute: DecisionsRoute,
  DifferencingRoute: DifferencingRoute,
  FederatedRoute: FederatedRoute,
  GuidedRoute: GuidedRoute,
  HealthRoute: HealthRoute,
  InfrastructureRoute: InfrastructureRoute,
  LedgerRoute: LedgerRoute,
  MlRoute: MlRoute,
  MonitorRoute: MonitorRoute,
  OverviewRoute: OverviewRoute,
  PipelineRoute: PipelineRoute,
  PolicyRoute: PolicyRoute,
  PrevalenceRoute: PrevalenceRoute,
  ThreatRoute: ThreatRoute,
  TradeoffRoute: TradeoffRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
